// lib/coaches.ts
// 2025-26 NBA head coaching data for all 30 teams.
// Records current as of the 2025-26 season (source: Wikipedia / Basketball-Reference).
// h2hVsKnicksCoach tracks NYK wins/losses vs each coach under Mike Brown (hired July 2025).
// Brown is in his first season as Knicks coach; most matchups show 0-0 (First Matchup).

export type Coach = {
  tricode: string;
  name: string;
  teamName: string;
  /** Total seasons as NBA head coach (full or partial) */
  experience: number;
  /** Career regular season win percentage, 0–100 */
  winPct: number;
  playoffRecord: { w: number; l: number };
  /** 2–3 word style label */
  style: string;
  /** One-sentence scouting note */
  scoutingNote: string;
  /** Head-to-head record vs Mike Brown / Knicks since 2025-26 season */
  h2hVsKnicksCoach: { nykW: number; nykL: number };
};

export const COACHES: Record<string, Coach> = {
  ATL: {
    tricode: 'ATL',
    name: 'Quin Snyder',
    teamName: 'Atlanta Hawks',
    experience: 12,
    winPct: 55.3,
    playoffRecord: { w: 37, l: 42 },
    style: 'Motion Offense',
    scoutingNote: 'Emphasizes off-ball movement and layered spacing; his offenses are meticulously designed to be difficult to scout night to night.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  BOS: {
    tricode: 'BOS',
    name: 'Joe Mazzulla',
    teamName: 'Boston Celtics',
    experience: 3,
    winPct: 73.0,
    playoffRecord: { w: 33, l: 17 },
    style: 'Fast Pace Offense',
    scoutingNote: 'Runs a positionless, high-tempo attack built around elite three-point volume and relentless off-ball cutting — 2024 NBA Champion.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  BKN: {
    tricode: 'BKN',
    name: 'Jordi Fernández',
    teamName: 'Brooklyn Nets',
    experience: 2,
    winPct: 32.2,
    playoffRecord: { w: 0, l: 0 },
    style: 'Player Development',
    scoutingNote: 'Second-year head coach prioritizing Brooklyn\'s youth movement through detailed positional schemes and systematic development.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  CHA: {
    tricode: 'CHA',
    name: 'Charles Lee',
    teamName: 'Charlotte Hornets',
    experience: 2,
    winPct: 27.1,
    playoffRecord: { w: 0, l: 0 },
    style: 'Defensive System',
    scoutingNote: 'Former Boston assistant importing championship-caliber defensive principles to an otherwise rebuilding Charlotte roster.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  CHI: {
    tricode: 'CHI',
    name: 'Billy Donovan',
    teamName: 'Chicago Bulls',
    experience: 14,
    winPct: 54.4,
    playoffRecord: { w: 19, l: 22 },
    style: 'Read & React',
    scoutingNote: 'Runs an adaptable read-and-react offense that stresses defensive rotations; favors versatile, IQ-driven lineups over rigid sets.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  CLE: {
    tricode: 'CLE',
    name: 'Kenny Atkinson',
    teamName: 'Cleveland Cavaliers',
    experience: 6,
    winPct: 47.4,
    playoffRecord: { w: 7, l: 8 },
    style: 'Pace and Space',
    scoutingNote: 'Known for developing young talent through pace-and-space principles, steadily transforming Cleveland into an Eastern Conference contender.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  DAL: {
    tricode: 'DAL',
    name: 'Jason Kidd',
    teamName: 'Dallas Mavericks',
    experience: 10,
    winPct: 50.9,
    playoffRecord: { w: 38, l: 34 },
    style: 'Iso Heavy',
    scoutingNote: 'Builds entirely around star isolation scoring while switching liberally on defense; led Dallas to the 2024 NBA Finals.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  DEN: {
    tricode: 'DEN',
    name: 'David Adelman',
    teamName: 'Denver Nuggets',
    experience: 1,
    winPct: 69.2,
    playoffRecord: { w: 3, l: 4 },
    style: 'Motion Offense',
    scoutingNote: 'Continues Denver\'s ball-movement identity around Nikola Jokic, adapting the Nuggets\' championship-winning system to a new staff.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  DET: {
    tricode: 'DET',
    name: 'J.B. Bickerstaff',
    teamName: 'Detroit Pistons',
    experience: 8,
    winPct: 49.2,
    playoffRecord: { w: 5, l: 12 },
    style: 'Physical Defense',
    scoutingNote: 'Emphasizes defensive toughness and second-chance points as he builds Detroit\'s identity around their young core.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  GSW: {
    tricode: 'GSW',
    name: 'Steve Kerr',
    teamName: 'Golden State Warriors',
    experience: 11,
    winPct: 64.3,
    playoffRecord: { w: 104, l: 48 },
    style: 'Motion Offense',
    scoutingNote: 'Architect of the modern NBA spacing revolution; four-time champion whose layered off-ball movement remains the league\'s gold standard.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  HOU: {
    tricode: 'HOU',
    name: 'Ime Udoka',
    teamName: 'Houston Rockets',
    experience: 4,
    winPct: 59.5,
    playoffRecord: { w: 16, l: 10 },
    style: 'Defensive Scheme',
    scoutingNote: 'Builds elite defensive cultures with physical switching principles while carefully developing Alperen Şengün\'s evolving offensive arsenal.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  IND: {
    tricode: 'IND',
    name: 'Rick Carlisle',
    teamName: 'Indiana Pacers',
    experience: 17,
    winPct: 52.9,
    playoffRecord: { w: 84, l: 89 },
    style: 'Read & React',
    scoutingNote: 'One of the NBA\'s foremost tacticians with 999+ career wins; exploits mismatches through meticulous pre-scout and precisely orchestrated movement.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  LAC: {
    tricode: 'LAC',
    name: 'Tyronn Lue',
    teamName: 'Los Angeles Clippers',
    experience: 6,
    winPct: 58.1,
    playoffRecord: { w: 55, l: 38 },
    style: 'Perimeter Oriented',
    scoutingNote: '2016 championship coach who favors quick ball movement and perimeter creation, highly effective at manipulating opponent coverage schemes.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  LAL: {
    tricode: 'LAL',
    name: 'JJ Redick',
    teamName: 'Los Angeles Lakers',
    experience: 2,
    winPct: 62.9,
    playoffRecord: { w: 1, l: 4 },
    style: 'Pace and Space',
    scoutingNote: 'Analytically-driven first-time head coach building a pace-and-space offense tailored around LeBron\'s playmaking and AD\'s interior dominance.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  MEM: {
    tricode: 'MEM',
    name: 'Tuomas Iisalo',
    teamName: 'Memphis Grizzlies',
    experience: 1,
    winPct: 44.4,
    playoffRecord: { w: 0, l: 0 },
    style: 'High Pace Offense',
    scoutingNote: 'Finnish coach running a high-pace, three-point-heavy system with intense short rotations; building his identity around a young Memphis core.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  MIA: {
    tricode: 'MIA',
    name: 'Erik Spoelstra',
    teamName: 'Miami Heat',
    experience: 17,
    winPct: 57.8,
    playoffRecord: { w: 110, l: 83 },
    style: 'Zone Defense',
    scoutingNote: 'Master tactician famed for Heat Culture; deploys zone looks and relentless conditioning that disrupt rhythm and crush opponent offenses.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  MIL: {
    tricode: 'MIL',
    name: 'Doc Rivers',
    teamName: 'Milwaukee Bucks',
    experience: 22,
    winPct: 58.5,
    playoffRecord: { w: 114, l: 112 },
    style: 'Defensive Scheme',
    scoutingNote: '2008 champion with 1,100+ career wins; uses size and switching versatility to clog the paint and best results with elite defensive anchors.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  MIN: {
    tricode: 'MIN',
    name: 'Chris Finch',
    teamName: 'Minnesota Timberwolves',
    experience: 5,
    winPct: 57.4,
    playoffRecord: { w: 10, l: 12 },
    style: 'Pick & Roll Heavy',
    scoutingNote: 'Leverages Rudy Gobert\'s screening in layered pick-and-roll actions that stress even elite defenses and create consistent half-court offense.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  NOP: {
    tricode: 'NOP',
    name: 'James Borrego',
    teamName: 'New Orleans Pelicans',
    experience: 8,
    winPct: 43.1,
    playoffRecord: { w: 6, l: 8 },
    style: 'Motion Offense',
    scoutingNote: 'Named interim after Willie Green\'s firing; immediately improved New Orleans\'s offense with ball-movement principles honed over 8 head-coaching seasons.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  NYK: {
    tricode: 'NYK',
    name: 'Mike Brown',
    teamName: 'New York Knicks',
    experience: 13,
    winPct: 60.1,
    playoffRecord: { w: 50, l: 40 },
    style: 'Defensive System',
    scoutingNote: 'Two-time unanimous Coach of the Year who builds elite defensive cultures; hired July 2025 to replace Thibodeau and bring championship structure to New York.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  OKC: {
    tricode: 'OKC',
    name: 'Mark Daigneault',
    teamName: 'Oklahoma City Thunder',
    experience: 5,
    winPct: 55.2,
    playoffRecord: { w: 15, l: 16 },
    style: 'System Basketball',
    scoutingNote: 'Designed OKC\'s historically deep, team-oriented offense and elite switchable defense; among the fastest-rising coaching minds in the league.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  ORL: {
    tricode: 'ORL',
    name: 'Jamahl Mosley',
    teamName: 'Orlando Magic',
    experience: 5,
    winPct: 44.9,
    playoffRecord: { w: 1, l: 4 },
    style: 'Defensive Identity',
    scoutingNote: 'Built Orlando\'s identity around elite interior defense — uses length and athleticism to make the paint uninhabitable for opposing offenses.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  PHI: {
    tricode: 'PHI',
    name: 'Nick Nurse',
    teamName: 'Philadelphia 76ers',
    experience: 6,
    winPct: 53.9,
    playoffRecord: { w: 43, l: 40 },
    style: 'Defensive Scheme',
    scoutingNote: '2019 champion renowned for physical switching defense and unconventional offensive sets that force opponents to over-prepare.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  PHX: {
    tricode: 'PHX',
    name: 'Jordan Ott',
    teamName: 'Phoenix Suns',
    experience: 1,
    winPct: 58.3,
    playoffRecord: { w: 0, l: 0 },
    style: 'Player Development',
    scoutingNote: 'First-year head coach with 20 years of assistant experience; building a structured, accountability-driven identity around a rebuilding Suns roster.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  POR: {
    tricode: 'POR',
    name: 'Tiago Splitter',
    teamName: 'Portland Trail Blazers',
    experience: 1,
    winPct: 47.2,
    playoffRecord: { w: 0, l: 0 },
    style: 'European System',
    scoutingNote: 'Former Spurs champion and Paris Basketball head coach; named interim after Billups\' departure, emphasizing European-influenced fundamentals.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  SAC: {
    tricode: 'SAC',
    name: 'Doug Christie',
    teamName: 'Sacramento Kings',
    experience: 2,
    winPct: 39.8,
    playoffRecord: { w: 0, l: 4 },
    style: 'Fast Pace Offense',
    scoutingNote: 'Former Kings legend preserving Sacramento\'s run-and-gun identity as the franchise manages a roster and front-office transition.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  SAS: {
    tricode: 'SAS',
    name: 'Mitch Johnson',
    teamName: 'San Antonio Spurs',
    experience: 1,
    winPct: 50.4,
    playoffRecord: { w: 0, l: 0 },
    style: 'Player Development',
    scoutingNote: 'Pop\'s longtime lieutenant now formally in charge; building the entire program around Victor Wembanyama with no short-term pressure to win.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  TOR: {
    tricode: 'TOR',
    name: 'Darko Rajaković',
    teamName: 'Toronto Raptors',
    experience: 3,
    winPct: 38.3,
    playoffRecord: { w: 0, l: 0 },
    style: 'European System',
    scoutingNote: 'Serbian-born coach bringing creative ball-screen actions and a meticulous player-development philosophy to a rebuilding Toronto roster.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  UTA: {
    tricode: 'UTA',
    name: 'Will Hardy',
    teamName: 'Utah Jazz',
    experience: 4,
    winPct: 34.5,
    playoffRecord: { w: 0, l: 0 },
    style: 'System Basketball',
    scoutingNote: 'One of the NBA\'s youngest coaches; methodically building Utah\'s culture around Lauri Markkanen through structured half-court systems.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
  WAS: {
    tricode: 'WAS',
    name: 'Brian Keefe',
    teamName: 'Washington Wizards',
    experience: 2,
    winPct: 23.1,
    playoffRecord: { w: 0, l: 0 },
    style: 'Player Development',
    scoutingNote: 'Overseeing a full rebuild centered on Alexandre Sarr and Jordan Poole; results are secondary to developing Washington\'s long-term assets.',
    h2hVsKnicksCoach: { nykW: 0, nykL: 0 },
  },
};

export function getCoach(tricode: string): Coach | undefined {
  return COACHES[tricode];
}
